export const GET_LIST_CHANNEL = "GET_LIST_CHANNEL";

export const GET_LIST_VIDEO_FROM_CHANNEL = "GET_LIST_VIDEO_FROM_CHANNEL";

export const GET_LIST_TBL_ACCOUNT = "GET_LIST_TBL_ACCOUNT";

export const GET_LIST_PLAYLIST_FROM_CHANNEL = "GET_LIST_PLAYLIST_FROM_CHANNEL";

export const GET_LIST_VIDEO_FROM_PLAYLIST = "GET_LIST_VIDEO_FROM_PLAYLIST";

// export type GET_LIST_CHANNEL = typeof GET_LIST_CHANNEL;
